var players = [
    {
        "playerId": 5648,
        "fullName": "Quinton de Kock (wk)",
        "firstName": "Quinton",
        "lastName": "de Kock",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/South%20Africa/Quinton-de-Kock-CWC19.ashx",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Does Not Bowl",
        "playerType": "Wicketkeeper",
        "dob": "1992-12-17T00:00:00Z",
        "testDebutDate": "2014-02-20T00:00:00Z",
        "odiDebutDate": "2013-01-19T00:00:00Z",
        "t20DebutDate": "2012-12-21T00:00:00Z",
        "bio": "<p>Quinton de Kock had achieved more by his 21<sup>st</sup> birthday than many cricketers do in their career.</p>\n<p class=\"p1\">The wicketkeeper has caused plenty of excitement not only for his skills behind the stumps, but for his considerable talent with the bat as well.</p>\n<p class=\"p1\">de Kock first made his mark on the South Africa Under-19 team, where he was a stand-out batsman, before he earned his first senior selection for the Proteas&rsquo; in a T20I clash with New Zealand in 2012.</p>\n<p class=\"p1\">A spot in South Africa&rsquo;s one-day squad soon followed, and de Kock made a significant breakthrough with his first one-day international century against Pakistan in 2013.</p>\n<p class=\"p1\">The left-hander blazed his way to five centuries in his first 19 ODI appearances, becoming the first player to score three successive one-day centuries and the second player to score four ODI centuries before his 21<sup>st</sup> birthday.</p>\n<p class=\"p1\">de Kock made his Test debut for the Proteas and made three centuries in his first 15 matches.</p>\n<p class=\"p1\">As a result, de Kock has quickly become a household name not only in South Africa, but around the world.</p>",
        "didYouKnow": "<p class=\"p1\">Shares his record of four ODI centuries before the age of 21 with Irish cricketer Paul Stirling.</p>",
        "height": ""
    },
    {
        "playerId": 3788,
        "fullName": "Virat Kohli (c)",
        "firstName": "Virat",
        "lastName": "Kohli",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/ODIWC19/Virat-Kohli-CWC19.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Medium",
        "playerType": "Batter",
        "dob": "1988-11-05T00:00:00Z",
        "testDebutDate": "2011-06-20T00:00:00Z",
        "odiDebutDate": "2008-08-18T00:00:00Z",
        "t20DebutDate": "2010-06-12T00:00:00Z",
        "bio": "<p><span style=\"color: #363636;\">There&rsquo;s a very good reason Virat Kohli is referred to as the &lsquo;King&rsquo;. The Indian captain&rsquo;s batting record is hardly matched by any other cricketer on the planet, with his aggressive approach to the game also making him a player fans flock to watch.</span></p>\n<p><span style=\"color: #363636;\"></span><span style=\"color: #363636; background-color: white;\">Kohli always dreamed of representing his country in cricket and had his first opportunity as a teenager when he played for the India under-19 team in 2006, guiding the same team to a World Cup win in 2008.</span></p>\n<p style=\"background: white; margin: 0cm 0cm 12pt;\"><span style=\"color: #363636;\">His senior international career took off soon after when Kohli made his one-day international debut against Sri Lanka in August 2008. He now has more than 35 one-day hundreds and many other fine performances to his name, with a high-score of 183 against Pakistan in 2012. He averages more than 50 in 50-over cricket.</span></p>\n<p> <span style=\"color: #363636;\">Kohli has been equally as impressive in the five-day game. He averages over 50 and has made 17 centuries and 14 fifties in 59 Tests. As of January 2019, he was the #1 ranked batsman in the world in both the ODI and Test formats. <br />\n<br />\nKohli&rsquo;s brilliance with the bat is matched by his skills as a captain in all three forms of the game. While a major tournament win still eludes the Indian&rsquo;s under his leadership, the side has regularly held the #1 world ranking in both Test and ODI cricket. He has the greatest Test Match winning percentage as an Indian captain, with a most recent triumph being a 2-1 series victory against Australia &ndash; the first ever Indian series win on Australian soil.</span></p>",
        "didYouKnow": "<p>Kohli was once named as one of&nbsp;GQ magazine&rsquo;s best dressed international sportsmen.</p>",
        "height": "175"
    },
    {
        "playerId": 3788,
        "fullName": "Rohit Sharma (c)",
        "firstName": "Rohit",
        "lastName": "Sharma",
        "imageURL": "https://akm-img-a-in.tosshub.com/indiatoday/images/media_bank/202308/rohit-sharma-071855-1x1_5.jpg?VersionId=rMcq8sFbaN9SbMdJHhkddIqEL9OiudHb",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Off Spin",
        "playerType": "Batter",
        "dob": "1988-11-05T00:00:00Z",
        "testDebutDate": "2011-06-20T00:00:00Z",
        "odiDebutDate": "2008-08-18T00:00:00Z",
        "t20DebutDate": "2010-06-12T00:00:00Z",
        "bio": "<p><span style=\"color: #363636;\">There&rsquo;s a very good reason Virat Kohli is referred to as the &lsquo;King&rsquo;. The Indian captain&rsquo;s batting record is hardly matched by any other cricketer on the planet, with his aggressive approach to the game also making him a player fans flock to watch.</span></p>\n<p><span style=\"color: #363636;\"></span><span style=\"color: #363636; background-color: white;\">Kohli always dreamed of representing his country in cricket and had his first opportunity as a teenager when he played for the India under-19 team in 2006, guiding the same team to a World Cup win in 2008.</span></p>\n<p style=\"background: white; margin: 0cm 0cm 12pt;\"><span style=\"color: #363636;\">His senior international career took off soon after when Kohli made his one-day international debut against Sri Lanka in August 2008. He now has more than 35 one-day hundreds and many other fine performances to his name, with a high-score of 183 against Pakistan in 2012. He averages more than 50 in 50-over cricket.</span></p>\n<p> <span style=\"color: #363636;\">Kohli has been equally as impressive in the five-day game. He averages over 50 and has made 17 centuries and 14 fifties in 59 Tests. As of January 2019, he was the #1 ranked batsman in the world in both the ODI and Test formats. <br />\n<br />\nKohli&rsquo;s brilliance with the bat is matched by his skills as a captain in all three forms of the game. While a major tournament win still eludes the Indian&rsquo;s under his leadership, the side has regularly held the #1 world ranking in both Test and ODI cricket. He has the greatest Test Match winning percentage as an Indian captain, with a most recent triumph being a 2-1 series victory against Australia &ndash; the first ever Indian series win on Australian soil.</span></p>",
        "didYouKnow": "<p>Kohli was once named as one of&nbsp;GQ magazine&rsquo;s best dressed international sportsmen.</p>",
        "height": "175"
    },
    {
        "playerId": 3788,
        "fullName": "Shreyas Iyer",
        "firstName": "Shreyas",
        "lastName": "Iyer",
        "imageURL": "http://t1.gstatic.com/images?q=tbn:ANd9GcT6ihw2CdS2NJXIkMG1QZsMmprMxDlMLalEfZE1L_lspIA9AYFyNFDoB6hzzf2t_6ajsShLEQ",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Leg Spin",
        "playerType": "Batter",
        "dob": "1988-11-05T00:00:00Z",
        "testDebutDate": "2011-06-20T00:00:00Z",
        "odiDebutDate": "2008-08-18T00:00:00Z",
        "t20DebutDate": "2010-06-12T00:00:00Z",
        "bio": "<p><span style=\"color: #363636;\">There&rsquo;s a very good reason Virat Kohli is referred to as the &lsquo;King&rsquo;. The Indian captain&rsquo;s batting record is hardly matched by any other cricketer on the planet, with his aggressive approach to the game also making him a player fans flock to watch.</span></p>\n<p><span style=\"color: #363636;\"></span><span style=\"color: #363636; background-color: white;\">Kohli always dreamed of representing his country in cricket and had his first opportunity as a teenager when he played for the India under-19 team in 2006, guiding the same team to a World Cup win in 2008.</span></p>\n<p style=\"background: white; margin: 0cm 0cm 12pt;\"><span style=\"color: #363636;\">His senior international career took off soon after when Kohli made his one-day international debut against Sri Lanka in August 2008. He now has more than 35 one-day hundreds and many other fine performances to his name, with a high-score of 183 against Pakistan in 2012. He averages more than 50 in 50-over cricket.</span></p>\n<p> <span style=\"color: #363636;\">Kohli has been equally as impressive in the five-day game. He averages over 50 and has made 17 centuries and 14 fifties in 59 Tests. As of January 2019, he was the #1 ranked batsman in the world in both the ODI and Test formats. <br />\n<br />\nKohli&rsquo;s brilliance with the bat is matched by his skills as a captain in all three forms of the game. While a major tournament win still eludes the Indian&rsquo;s under his leadership, the side has regularly held the #1 world ranking in both Test and ODI cricket. He has the greatest Test Match winning percentage as an Indian captain, with a most recent triumph being a 2-1 series victory against Australia &ndash; the first ever Indian series win on Australian soil.</span></p>",
        "didYouKnow": "<p>Kohli was once named as one of&nbsp;GQ magazine&rsquo;s best dressed international sportsmen.</p>",
        "height": "175"
    },
    {
        "playerId": 3788,
        "fullName": "Sanju Samson",
        "firstName": "Sanju",
        "lastName": "Samson",
        "imageURL": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcScFieYt9kAZmy0tZ72I_iWgeKzRivfB_pY8WFryGGVyYlR9wib",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Medium",
        "playerType": "Batter",
        "dob": "1988-11-05T00:00:00Z",
        "testDebutDate": "2011-06-20T00:00:00Z",
        "odiDebutDate": "2008-08-18T00:00:00Z",
        "t20DebutDate": "2010-06-12T00:00:00Z",
        "bio": "<p><span style=\"color: #363636;\">There&rsquo;s a very good reason Virat Kohli is referred to as the &lsquo;King&rsquo;. The Indian captain&rsquo;s batting record is hardly matched by any other cricketer on the planet, with his aggressive approach to the game also making him a player fans flock to watch.</span></p>\n<p><span style=\"color: #363636;\"></span><span style=\"color: #363636; background-color: white;\">Kohli always dreamed of representing his country in cricket and had his first opportunity as a teenager when he played for the India under-19 team in 2006, guiding the same team to a World Cup win in 2008.</span></p>\n<p style=\"background: white; margin: 0cm 0cm 12pt;\"><span style=\"color: #363636;\">His senior international career took off soon after when Kohli made his one-day international debut against Sri Lanka in August 2008. He now has more than 35 one-day hundreds and many other fine performances to his name, with a high-score of 183 against Pakistan in 2012. He averages more than 50 in 50-over cricket.</span></p>\n<p> <span style=\"color: #363636;\">Kohli has been equally as impressive in the five-day game. He averages over 50 and has made 17 centuries and 14 fifties in 59 Tests. As of January 2019, he was the #1 ranked batsman in the world in both the ODI and Test formats. <br />\n<br />\nKohli&rsquo;s brilliance with the bat is matched by his skills as a captain in all three forms of the game. While a major tournament win still eludes the Indian&rsquo;s under his leadership, the side has regularly held the #1 world ranking in both Test and ODI cricket. He has the greatest Test Match winning percentage as an Indian captain, with a most recent triumph being a 2-1 series victory against Australia &ndash; the first ever Indian series win on Australian soil.</span></p>",
        "didYouKnow": "<p>Kohli was once named as one of&nbsp;GQ magazine&rsquo;s best dressed international sportsmen.</p>",
        "height": "175"
    },
    {
        "playerId": 3241,
        "fullName": "AB de Villiers",
        "firstName": "Abraham",
        "lastName": "de Villiers",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/South%20Africa/AB-de-Villiers-CT17.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Medium",
        "playerType": "Batter",
        "dob": "1984-02-17T00:00:00Z",
        "testDebutDate": "2004-12-17T00:00:00Z",
        "odiDebutDate": "2005-02-02T00:00:00Z",
        "t20DebutDate": "2006-02-24T00:00:00Z",
        "bio": "<p>Without a doubt one of the world&rsquo;s leading batsmen, AB de Villiers continues to dominate all three formats when he can get on the park for South Africa.</p>\n<p class=\"p1\">Since his debut in 2004, the Proteas batter has proven his ability to score runs anywhere in the order and averages more than 50 in Test and ODI cricket.</p>\n<p class=\"p1\">AB de Villiers and Hashim Amla broke the OCI third wicket all-time partnership in 2013 when they combined for 238 against Pakistan, while he is also the joint second-fastest batsman in cricket&rsquo;s history to score 6000 ODI runs.</p>\n<p class=\"p1\">de Villiers had an outstanding 2011 World Cup scoring 353 runs in five matches to average 88.25 and became only the fifth player in the tournament&rsquo;s history to score consecutive centuries.</p>\n<p class=\"p1\">He took over the one-day captaincy role from Graeme Smith in June 2011 before stepping down in December 2016.</p>\n<p class=\"p1\">In January 2015, de Villiers scored the fastest ODI century in history, reaching three figures from 31 deliveries and has made 21 Test and 24 ODI hundreds for his country.</p>",
        "didYouKnow": "<p class=\"p1\">Was shortlisted for national junior hockey and soccer squads, captained the national junior rugby team and was a member of South Africa&rsquo;s junior Davis Cup team.</p>",
        "height": ""
    },
    {
        "playerId": 5977,
        "fullName": "Corey Anderson",
        "firstName": "Corey",
        "lastName": "Anderson",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/New%20Zealand/Corey-Anderson-CT17.ashx",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Left Arm Med-Fast",
        "playerType": "Allrounder",
        "dob": "1990-12-13T00:00:00Z",
        "testDebutDate": "2013-10-09T00:00:00Z",
        "odiDebutDate": "2013-06-16T00:00:00Z",
        "t20DebutDate": "2012-12-21T00:00:00Z",
        "bio": "<p>An allrounder with plenty of potential, Corey Anderson was quick to make an impression on world cricket in his first 12 months of international cricket.</p>\n<p>The Christchurch-born player made his one-day international debut against England in mid-2013 and has since scored more than 450 runs with an average above 36 and a strike rate above 150.</p>\n<p>In January 2014 Anderson set a record for the fastest ODI century when he reached three figures off 36 balls against West Indies.&nbsp;</p>\n<p>Later that same month, he took 5-64 against India to show his genuine all-round talent.</p>\n<p>Anderson made his Test debut in October 2013 against Bangladesh and scored one century, one fifty and took 13 wickets in his first nine matches.</p>",
        "didYouKnow": "<P>He scored an ODI century off 36 balls in January 2014.</p>",
        "height": ""
    },
    {
        "playerId": 5156,
        "fullName": "Colin de Grandhomme",
        "firstName": "Colin",
        "lastName": "de Grandhomme",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/New%20Zealand/Colin-de-Grandhomme-CWC19.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Fast-Med",
        "playerType": "Allrounder",
        "dob": "1986-07-22T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "0001-01-01T00:00:00Z",
        "t20DebutDate": "0001-01-01T00:00:00Z",
        "bio": "",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 8240,
        "fullName": "Washington Sundar",
        "firstName": "Washington",
        "lastName": "Sundar",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Right Arm Off-Spin",
        "playerType": "Allrounder",
        "dob": "1999-10-05T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "0001-01-01T00:00:00Z",
        "t20DebutDate": "0001-01-01T00:00:00Z",
        "bio": "",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 5331,
        "fullName": "Pawan Negi",
        "firstName": "Pawan",
        "lastName": "Negi",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/Pawan-Negi-wt20.ashx",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Left Arm Orthodox",
        "playerType": "Bowler",
        "dob": "1993-01-06T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "0001-01-01T00:00:00Z",
        "t20DebutDate": "2016-03-01T00:00:00Z",
        "bio": "<p>Pawan Negi made is T20I debut against the UAE in Dhaka. He took 1-16 from his three overs.</p>\n<p>Despite being predominately a bowler, Negi has a list-A century, 124 not out.</p>",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 4395,
        "fullName": "Umesh Yadav",
        "firstName": "Umeshkumar",
        "lastName": "Yadav",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/Umesh-Yadav-CT17.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Fast-Med",
        "playerType": "Bowler",
        "dob": "1987-10-25T00:00:00Z",
        "testDebutDate": "2011-11-06T00:00:00Z",
        "odiDebutDate": "2010-05-28T00:00:00Z",
        "t20DebutDate": "2012-08-07T00:00:00Z",
        "bio": "<p>Umesh Yadav is the definition of a &lsquo;late bloomer&rsquo;. He only started playing cricket as a 19-year-old but his natural talent for bowling fast meant he was quick to make up for lost time.&nbsp;</p>\n<p>Yadav made his debut for Vidharbha in 2008 and soon found himself bowling to some of the big names in Indian cricket on the domestic circuit.</p>\n<p>His one-day international debut followed in 2010 in a tri-series in Zimbabwe but only picked up one wicket in three outings. Yadav&rsquo;s next chance came more than a year later against England where his results improved and he has been a regular member of the national side since. His pace combined with an ability to swing the ball both ways has made him a handy addition to the squad.</p>\n<p>Yadav&rsquo;s opportunities in the Test arena have been more limited, with the quick playing nine matches in 2011 and 2012. He came back in to favour in 2014 and has played more than 30 Test and taken one five-wicket haul.</p>\n<p>&nbsp;</p>\n<div>&nbsp;</div>",
        "didYouKnow": "Before becoming a professional cricketer, he wanted to join the army or become a police officer.",
        "height": ""
    },
    {
        "playerId": 11100,
        "fullName": "Mohammed Siraj",
        "firstName": "Mohammed",
        "lastName": "Siraj",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Med-Fast",
        "playerType": "Bowler",
        "dob": "1994-03-13T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "0001-01-01T00:00:00Z",
        "t20DebutDate": "0001-01-01T00:00:00Z",
        "bio": "",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 5085,
        "fullName": "Yuzvendra Chahal",
        "firstName": "Yuzvendra",
        "lastName": "Chahal",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/ODIWC19/Yuvendra-Chahal-CWC19.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Leg-Spin",
        "playerType": "Bowler",
        "dob": "1990-07-23T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "0001-01-01T00:00:00Z",
        "t20DebutDate": "0001-01-01T00:00:00Z",
        "bio": "",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 3017,
        "fullName": "Shane Watson",
        "firstName": "Shane",
        "lastName": "Watson",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/Domestic/Sydney%20Thunder/BBL08/Shane_Watson_BBL08.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Medium",
        "playerType": "Allrounder",
        "dob": "1981-06-17T00:00:00Z",
        "testDebutDate": "2005-02-01T00:00:00Z",
        "odiDebutDate": "2002-03-24T00:00:00Z",
        "t20DebutDate": "2006-02-24T00:00:00Z",
        "bio": "<p>Since his international debut in an ODI against South Africa in 2002, Australian cricket fans have ridden the rollercoaster that is Shane Watson&rsquo;s injury-filled career. </p>\n<p>Despite appearing to have a strong physique, Watson&rsquo;s body has failed him numerous times over his career. However continuous disappointment has not shaken his determination to be successful at cricket&rsquo;s top level. </p>\n<p>Watson made his Test debut in 2005 against Pakistan, batting at no.7 with a top score of 31, and taking the wicket of Younis Khan in a win for the Aussies. He has moved up and down the batting order in his Test career, even opening the batting in 2009 which triggered a memorable run of form for Watson. This included passing 50 eight times in as many innings, as well as his maiden Test century. Other highlights include a patient hundred on a dustbowl in Mohali in 2010, his almost flawless innings of 176 against at The Oval in 2013 and his run-a-ball century against England in Perth just a few months later.</p>\n<p>There have been several stand-out moments in the coloured clothing as well, both for Australia and in the IPL, with the highlight of his ODI career coming when he smashed an unbeaten 185 from 96 balls against Bangladesh in 2011. His back-to-back Test five-wicket hauls against Pakistan in 2010 also proves that he can be much more than a change bowler when his fragile body allows.</p>\n<p>Watson was a member of the winning ICC World Cup team in 2014-15, and has represented Australia at the ICC World T20. He is also a two-time Allan Border medalist.</p>\n<p> </p>\n<p></p>",
        "didYouKnow": "Attended the same school as Australia&rsquo;s famed rugby league brothers Kevin, Kerrod and Steve Walters, former Wallabies vice-captain Berrick Barnes, tennis legend Roy Emerson and ex-Australian fast bowler Craig McDermott.",
        "height": "183"
    },
    {
        "playerId": 4620,
        "fullName": "Ambati Rayudu",
        "firstName": "Ambati",
        "lastName": "Rayudu",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/ambati-tayudu-ind.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Off-Spin",
        "playerType": "Wicketkeeper",
        "dob": "1985-09-23T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "2013-07-24T00:00:00Z",
        "t20DebutDate": "2014-09-07T00:00:00Z",
        "bio": "<p>Ambati Rayudu has a wonderful ODI record for India in his 34-match career. He averages more than 50 with a highest score of 124 not out.</p>\n<p>The talented batsman has also represented India in T20Is, debuting against England in 2014.</p>\n<p>Having earned a reputation as someone with the ability to finish off games from crunch situations, Rayudu scored his maiden ODI ton in November 2014 against Sri Lanka when he smashed an unbeaten 121 from 118 balls.</p>\n<p>He first came to the attention of cricket followers in 2001 when he attended the National Cricket Academy and scored an unbeaten 177 for India Colts against England in 2002.</p>\n<div>&nbsp;</div>",
        "didYouKnow": "His unbeaten 63 on debut at age 27 years and 304 days made him the third-oldest Indian to score a fifty on ODI debut.",
        "height": ""
    },
    {
        "playerId": 3287,
        "fullName": "Suresh Raina",
        "firstName": "Suresh",
        "lastName": "Raina",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/Suresh-Raina-wt20.ashx",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Right Arm Off-Spin",
        "playerType": "Batter",
        "dob": "1986-11-27T00:00:00Z",
        "testDebutDate": "2010-06-26T00:00:00Z",
        "odiDebutDate": "2005-07-30T00:00:00Z",
        "t20DebutDate": "2006-12-01T00:00:00Z",
        "bio": "<p>An aggressive left-handed batsman with more than 200 one-day international caps to his name, Suresh Raina has focused his career on the limited-overs formats.</p>\n<p>He has grown steadily since his ODI debut in 2006 and averaged mid-30s with more than 30 fifties to his name.</p>\n<p>A strike rate in the 90s makes him a dangerous one-day prospect, while Raina has also had success on the T20 circuit, where his strike rate is in the mid-130s.</p>\n<p>His Test call-up came in mid-2013 and the left-handed batsman made an instant impression scoring a century on debut, but fell out of favour with selectors after 18 Tests.</p>",
        "didYouKnow": "He has stepped in as India captain on several occasions, including during the West Indies tour in 2011 and against Bangladesh in 2014.",
        "height": ""
    },
    {
        "playerId": 4718,
        "fullName": "Sam Billings",
        "firstName": "Samuel",
        "lastName": "Billings",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/England/T20/Sam-Billings-T2018.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "",
        "playerType": "Batter",
        "dob": "1991-06-15T00:00:00Z",
        "testDebutDate": "0001-01-01T00:00:00Z",
        "odiDebutDate": "2015-06-09T00:00:00Z",
        "t20DebutDate": "2015-06-23T00:00:00Z",
        "bio": "<p>Even after playing just a handful of international games, it was evident Sam Billings was a shot maker who wasn&rsquo;t afraid to take on a bowling attack.</p>\n<div>The middle-order batsman made his debut for England against New Zealand in an ODI at Edgbaston in 2015. Scores of 41 and 53 were highlights for the Kent batsman that year, before he was selected for the 2016 World T20 squad in India.</div>\n<div>&nbsp;</div>\n<div>Billings also debuted for England in T20 cricket in 2016, making 53 in his third innings.\n</div>",
        "didYouKnow": "<p style=\"text-indent: -18pt;\"></p>",
        "height": ""
    },
    {
        "playerId": 3243,
        "fullName": "MS Dhoni (c/wk)",
        "firstName": "Mahendra",
        "lastName": "Dhoni",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/ODIWC19/MS-Dhoni-CWC19.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Medium",
        "playerType": "Wicketkeeper",
        "dob": "1981-07-07T00:00:00Z",
        "testDebutDate": "2005-12-02T00:00:00Z",
        "odiDebutDate": "2004-12-23T00:00:00Z",
        "t20DebutDate": "2006-12-01T00:00:00Z",
        "bio": "<p>Inspirational captain, talented batsman and skilled wicketkeeper. There have been no shortage of accolades for MS Dhoni since he made his international debut in 2004.</p>\n<p>Dhoni announced himself in only his fifth one-day international appearance in 2005 when he blasted his way to 148 off 123 balls and his ODI high-score of 183 not out came later the same year.</p>\n<p>He was&nbsp;arguably India&rsquo;s most successful captain with a record that includes leading his side to victory in the ICC Cricket World Cup 2011, taking India to the top of the Test rankings for 18 months from December 2009 and winning the ICC World Twenty20 in 2007.</p>\n<p>Dhoni made 64 ODI fiftes to go along with his 10 centuries and an average of above 51.</p>\n<p>While his Test career wasn't as prolific as his one-day career, it is still extremely prosperous. He made six centuries and 33 fifties with a high-score of 224.</p>",
        "didYouKnow": "He worked as a railway ticket collector before rising to stardom.",
        "height": ""
    },
    {
        "playerId": 3166,
        "fullName": "Dwayne Bravo",
        "firstName": "Dwayne",
        "lastName": "Bravo",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/Domestic/Melbourne%20Renegades/BBL07/Dwayne-Bravo-BBL07.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Med-Fast",
        "playerType": "Allrounder",
        "dob": "1983-10-07T15:45:00Z",
        "testDebutDate": "2004-07-22T00:00:00Z",
        "odiDebutDate": "2004-04-18T00:00:00Z",
        "t20DebutDate": "2006-02-16T00:00:00Z",
        "bio": "<p>One of the world&rsquo;s most entertaining players, Bravo has lit up T20 cricket around the world.&nbsp;</p>\n<p>In a three year period, he almost exclusively played T20s.&nbsp;</p>\n<p>Not many players can boast a T20 record of more than 200 wickets and 3000 runs but Bravo has held a high standard of cricket for over a decade.&nbsp;</p>\n<p>Bravo has a plethora of leadership experience, captaining his country in all three formats of the game.&nbsp;</p>\n<p>He has over 2000 Test, 2900 ODI runs to go with 86 and 199 wickets respectively.</p>\n<p> </p>",
        "didYouKnow": "<p>Dwayne's half-brother Darren also represented the West Indies.</p>",
        "height": ""
    },
    {
        "playerId": 3856,
        "fullName": "Ravindra Jadeja",
        "firstName": "Ravindrasinh",
        "lastName": "Jadeja",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/ODIWC19/Ravindra-Jadeja-CWC19.ashx",
        "battingStyle": "Left Hand",
        "bowlingStyle": "Left Arm Orthodox",
        "playerType": "Allrounder",
        "dob": "1988-12-06T00:00:00Z",
        "testDebutDate": "2012-12-13T00:00:00Z",
        "odiDebutDate": "2009-02-08T00:00:00Z",
        "t20DebutDate": "2009-02-10T00:00:00Z",
        "bio": "<p>After three years in the coloured clothes for India, Ravindra Jadeja finally earned his Test call-up in 2012.</p>\n<p>The allrounder has impressed many with his performances in limited-overs cricket since making his one-day international debut in 2009 against Sri Lanka and has secured his place as a key player in the India ODI line-up.</p>\n<p>His best ODI batting performance saw him score 87 against England in September 2014 while his best bowling figures of 5-36 came in mid-2013.</p>\n<p>Jadeja has impressed in Test cricket, taking  155 wickets in his first 32 Tests.</p>\n<p>His athleticism in the field completes the package.</p>",
        "didYouKnow": "In 2012 he became the eighth player in history and the first Indian player to score three first-class triple centuries in his career.",
        "height": ""
    },
    {
        "playerId": 2138,
        "fullName": "Harbhajan Singh",
        "firstName": "Harbhajan",
        "lastName": "Singh",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/India/Harbhajan-Singh-wt20.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Off-Spin",
        "playerType": "Bowler",
        "dob": "1980-07-03T00:00:00Z",
        "testDebutDate": "1998-03-25T00:00:00Z",
        "odiDebutDate": "1998-04-17T00:00:00Z",
        "t20DebutDate": "2006-12-01T00:00:00Z",
        "bio": "<p>Harbhajan Singh  caused Australia severe problems throughout his eventful career, both with his off-spin bowling and an aggressive attitude.&nbsp;</p>\n<p>The famous 2001 Test series was when Harbhajan emerged as a world-class operator, taking 32 wickets in three games.&nbsp;</p>\n<p>He has an amazing record against Ricky Ponting, dismissing the Australian legend 10 times.</p>\n<p>His teasing spin was often unplayable in India but, like most finger spinners, he struggled for success in Australia. Overall he has 417 wickets in 103 Tests and 269 in 236 ODIs.</p>\n<p>Harbhajan also recorded two Test centuries.</p>",
        "didYouKnow": "",
        "height": ""
    },
    {
        "playerId": 4166,
        "fullName": "Imran Tahir",
        "firstName": "Mohammad",
        "lastName": "Tahir",
        "imageURL": "https://www.cricket.com.au/-/media/Players/Men/International/South%20Africa/Imran-Tahir-CWC19.ashx",
        "battingStyle": "Right Hand",
        "bowlingStyle": "Right Arm Leg-Spin",
        "playerType": "Bowler",
        "dob": "1979-03-27T00:00:00Z",
        "testDebutDate": "2011-11-09T00:00:00Z",
        "odiDebutDate": "2011-02-24T00:00:00Z",
        "t20DebutDate": "2013-08-02T00:00:00Z",
        "bio": "<p>The old saying &lsquo;patience is a virtue&rsquo; certainly applies to Imran Tahir.</p>\n<p>Tahir, who was born in Pakistan, was chosen to play for South Africa in a Test against England in January 2010. But the Proteas were forced to withdraw him from their squad after discovering the former Pakistan A leg-spinner was not yet eligible to play for them.</p>\n<p>Instead, he had to wait until January 2011, before he qualified as a South African. Fortunately for the bowler, he did not have to wait much longer than that to represent his adopted country.</p>\n<p>The leg-spinner made his debut for the Proteas in the 2011 ICC Cricket World Cup, and impressed with 14 wickets in the five matches he played during that tournament.</p>\n<p>His ability to spin the ball gave South Africa greater versatility in the field in one-day international games, and while he spent some time on the sidelines in early 2012, he returned as a regular member of the ODI side in late 2013.</p>\n<p>Since starting his first-class career in 1996-97 Tahir has played for more than 10 teams, including Lahore, Yorkshire and the Titans in South Africa.&nbsp;</p>\n<p>He played 20 Tests for the Proteas and took 57 wickets including two five-wicket hauls.</p>",
        "didYouKnow": "Was born in Lahore, Pakistan, on March 27 1979.",
        "height": ""
    }
]